openapi: 3.0.0
servers:
  - url: "http://localhost:8080/"
info:
  description: Test API
  version: 1.0.0
  title: OpenAPI WooDOng
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: product
    description: Product CRUD
paths:
  /product:
    post:
      tags:
        - product
      summary: Add new product
      description: ""
      operationId: addProduct
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "405":
          description: Invalid input
      requestBody:
        $ref: "#/components/requestBodies/Product"
components:
  requestBodies:
    Product:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
      description: Product object that needs to be added to the product
      required: true
  schemas:
    Product:
      title: a Product
      description: Products
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Phone
        price:
          type: integer
          format: int64