name: openAPI_generate

on:
  pull_request:
    types:
      - closed

jobs:
  # 해당 PR Merge 후 실행
  if_merged:
    if: github.event.pull_request.merged == true

    # 빌드 환경 셋팅
    runs-on: ubuntu-latest

    steps:
      # 소스 가져오기
      - uses: actions/checkout@v3

      # Java 환경 셋팅
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
        run: java --version

      # Git 계정 로그인 ( PR 담당자 )
      - name: Configure git
        uses: dawidd6/action-git-user-config@v1
