name: openAPI_validate

on:
  pull_request:
    paths:
      - "src/server/apis/**"

jobs:
  # 해당 PR Merge 후 실행
  build:
    # 빌드 환경 셋팅
    runs-on: ubuntu-latest

    steps:
      # 소스 가져오기
      - uses: actions/checkout@v3

      # Java 환경 셋팅
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Document Validation
      - name: OpenAPI Document Validation
        run: |
          yarn install
          yarn workspace server oas-validate
