name: openAPI_generate

on:
  pull_request:
    types:
      - closed
    paths:
      - "src/server/apis/**"

jobs:
  # 해당 PR Merge 후 실행
  if_merged:
    if: github.event.pull_request.merged == true

    # 빌드 환경 셋팅
    runs-on: ubuntu-latest

    steps:
      # 소스 가져오기
      - uses: actions/checkout@v3

      # Java 환경 셋팅
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Git 계정 로그인 ( PR 담당자 )
      - uses: dawidd6/action-git-user-config@v1

      # Document Validation
      - name: OpenAPI Document Validation
        run: |
          yarn install
          yarn workspace server oas-validate

      # yarn generate script 실행
      - name: OpenAPI Generating
        run: |
          yarn workspace server generate

      # sdk/packages/sdk/apis/... 파일 변동 확인
      - name: Check Git status
        id: git
        shell: bash
        run: |
          RESULT=$(git status)
          if
            [[ $RESULT == *"src/client/api"* ]];
          then
            echo "generated successfully"
          else
            echo "generated faild"
            exit 1
          fi

      # commit 내역 남기기
      - uses: EndBug/add-and-commit@v9.0.0
        with:
          message: "feat: API 클라이언트 생성"
          add: "src/client/api"

      # 해당 PR에 Push
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TEST_SECRET }}
          branch: ${{ github.ref }}
